use_frameworks!

target 'XIKeyboardInputManager_Example' do
  pod 'XIKeyboardInputManager', :path => '../'
  pod 'XIProgressHUD'
  
  target 'XIKeyboardInputManager_Tests' do
    inherit! :search_paths

    
  end
end
